export const ROUTES = {
  HOME: "/",
  SHOP: "/products",
  PRODUCTS: "/products",
  PRODUCT_DETAIL: (id: string) => `/product/${id}`,
  CATEGORY: (slug: string) => `/products?category=${slug}`,
  SEARCH: (query: string) => `/products?search=${encodeURIComponent(query)}`,
  CART: "/cart",
  CHECKOUT: "/checkout/address",
  CHECKOUT_ADDRESS: "/checkout/address",
  CHECKOUT_PAYMENT: "/checkout/payment",
  CHECKOUT_SUCCESS: "/checkout/success",
  WISHLIST: "/wishlist",
  SALE: "/products?is_sale=true",
  TRENDING: "/products?is_trending_collection=true",
  TRACK_ORDER: "/track-order",
  ABOUT: "/about",
  HELP: "/help",
  LOGIN: "/login",
  SIGNUP: "/signup",
} as const;
